Update run-newman.yml

diff --git a/.github/workflows/run-newman.yml b/.github/workflows/run-newman.yml
--- a/.github/workflows/run-newman.yml
+++ b/.github/workflows/run-newman.yml
@@ -54,6 +54,11 @@ jobs:
               --reporter-html-export "$report_html" \
               --reporter-htmlextra-export "$report_htmlextra" -n 1
 
+            if [[ $? -ne 0 ]]; then
+              echo "❌ Error: Newman falló para el usuario $username"
+              exit 1
+            fi
+
             if [[ -f "$report_html" ]]; then
               echo "✅ Reporte HTML generado: $report_html"
             else
@@ -82,8 +87,9 @@ jobs:
           ls -R newman/
 
           echo "Subiendo reportes a S3..."
-<<<<<<< HEAD
           aws s3 cp newman/ s3://newman-uvilor/ --recursive
-=======
-          aws s3 cp newman/ s3://newman-uvilor/ --recursive
->>>>>>> 45e5334beecd40ac61e37c7398cb5eb02119a4f9
+
+          if [[ $? -ne 0 ]]; then
+            echo "❌ Error: Falló la subida de los reportes a S3"
+            exit 1
+          fi
